version: '3.7'

services:
  caliper:
    container_name: caliper
    image: hyperledger/caliper:0.6.0
    labels:
      service: hyperledger-caliper
    command: sudo chown -R 900:900 "/.npm" && launch manager
    environment:
      - CALIPER_WORKSPACE=/hyperledger/caliper/workspace/fabric-benchmarks
      - CALIPER_BIND_SUT=fabric:fabric-gateway
      - CALIPER_BENCHCONFIG=chaincode/medsky/config.yaml
      - CALIPER_NETWORKCONFIG=network.yaml
    volumes:
      - ../fabric-network:/hyperledger/caliper/workspace/fabric-network
      - ./:/hyperledger/caliper/workspace/fabric-benchmarks
    working_dir: /hyperledger/caliper/workspace/fabric-benchmarks